
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-local-pv
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    # Using local storage as persistent store. Kubelet is responsible for
    # checking the path and does mounting. Rancher has Kubelet running as
    # a container and the folder needs to be created in Kubelet docker
    # container first, or you maybe see the error below
    #            path "/mnt/local/mysql-local" does not exist
    path: /mnt/local/mysql-local
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/worker
          operator: In
          values:
          - "true"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-local-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
